modLoader = "javafml"
loaderVersion = "[45,)"
license = "All Rights Reserved"
issueTrackerURL = "https://github.com/MehVahdJukaar/${github_name}/issues"

[[mods]]
modId = "complementaries"
version = "${version}"
displayName = "Complementaries"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/complementaries"
logoFile = "icon.png"
authors = "MehVahdJukaar, Plantkillable, Alex Nijjar"
credits = ""
description = ""

[[dependencies.complementaries]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.complementaries]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.complementaries]]
modId = "resourcefullib"
mandatory = true
versionRange = "[${resourcefullib_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.complementaries]]
modId = "terrablender"
mandatory = true
versionRange = "[${terrablender_version},)"
ordering = "NONE"
side = "BOTH"